spring.application.name=Backend

# H2 In-Memory Database (Zero Config)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# MySQL Database Connection (Commented out)
# spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_platform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=Iradukunda03@

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Enable H2 Console (Access at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Master Admin Credentials (For DataSeeder)
# In local development, it reads from here. In production (Render), these are overridden by secure Environment Variables.
app.admin.email=systemadmin@ecom.rw
app.admin.password=systemadmin123
app.admin.name=System Administrator
app.admin.phone=0780000000

# File Upload Configuration
app.upload.dir=uploads/products
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Email Configuration (Mailtrap for Dev)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=88f98b2649a37e
spring.mail.password=********
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email

# Flutterwave Configuration
app.flutterwave.secret-key=FLWSECK_TEST-xxxxxxxxxxxxxxxxxxxx-X
app.flutterwave.webhook-secret=my_secret_hash_123
