spring.application.name=Backend

# Supabase PostgreSQL Connection (direct — most reliable for JPA/Hibernate)
spring.datasource.url=jdbc:postgresql://db.vapmkaqserarlncbvgac.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=E-commerce@Intern12
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driverClassName=org.postgresql.Driver



# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Enable H2 Console (Access at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Master Admin Credentials (For DataSeeder)
# In local development, it reads from here. In production (Render), these are overridden by secure Environment Variables.
app.admin.email=systemadmin@ecom.rw
app.admin.password=systemadmin123
app.admin.name=System Administrator
app.admin.phone=0780000000

# File Upload Configuration
app.upload.dir=uploads/products
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Email Configuration (Mailtrap for Dev)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=fca2c387195511
spring.mail.password=6c3668dfed5834
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=972194250845-dimcu02h7ip06hg36c0a27ggbqv9foop.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# Flutterwave Configuration 
app.flutterwave.secret-key=FLWSECK_TEST-2b4b9248f182634fdac27bd5661d17f4-X
app.flutterwave.webhook-secret=my_secret_hash_123
